### ISSUE TITLE
Zenodo badge is broken

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Associations.jl#388]
Something is wrong with the Zenodo DOI badge. It is broken. When I try to access the repo page in my Zenodo account it tells me "page not found". The current DOI points to CausalityTools.jl v2.1.

We should set up the badge so that it points to latest stable zenodo release, and make sure the release mentions "Associations.jl".

**Comment by kahaaga** [comment]
I got the same error as you in my Zenodo account, @Datseris. I then disconnected my GitHub account from the Zenodo account, re-connected it and re-synced the repos that Zenodo had access to. It now correctly finds the repo. 

<img width="967" alt="Screenshot 2024-08-09 at 20 04 25" src="https://github.com/user-attachments/assets/e9b1f16e-9a2d-4e67-98bd-4664a8f3aad1">

However, it does *not* point to the latest release. Not sure how to fix this...

**Comment by kahaaga** [comment]
<img width="962" alt="Screenshot 2024-08-09 at 20 06 06" src="https://github.com/user-attachments/assets/86cc6676-160a-4a7d-97a4-1f74889f9155">

Ah, I also had to enable the button in the top right corner. I think this should publish a new version when we do a new release here using JuliaRegistrator. Perhaps we could do a no-change release to 4.2.1 just to trigger the build, so that the badge points to the latest version?

**Comment by Datseris** [comment]
Ah no releases get sync in GitHub and the package manager due to tagbot. As soon as you have a commit you can trigger a new release and it will be fine!

**Comment by kahaaga** [comment]
The badge now works after the new release.
